velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0    # Hz (should match controller frequency)
    speed_lim_v: 0.3             # Max linear velocity (m/s)
    speed_lim_w: 1.57            # Max angular velocity (rad/s)
    accel_lim_v: 0.25            # Linear acceleration limit (m/s²)
    accel_lim_w: 0.8             # Angular acceleration limit (rad/s²)
    decel_lim_v: 0.25            # Linear deceleration limit (m/s²)
    decel_lim_w: 0.8             # Angular deceleration limit (rad/s²)
    odom_topic: /odom            # Odometry topic for feedback
    input_cmd_vel_topic: /cmd_vel_nav  # Input from Nav2 controller
    output_cmd_vel_topic: /cmd_vel     # Smoothed output to robot
